# Generated by Django 6.0.4 on 2026-04-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_is_paid_booking_refund_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('payment_confirmed', 'Paid'), ('pending_admin', 'Pending Admin Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_admin', max_length=30),
        ),
    ]
