# Generated by Django 6.0.4 on 2026-04-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='nearby_places',
            field=models.TextField(blank=True, null=True),
        ),
    ]
