# Generated by Django 6.0.4 on 2026-04-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_hotel_description_hotel_hotel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
