# Generated by Django 6.0.4 on 2026-04-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
