# Generated by Django 6.0.4 on 2026-04-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_trip_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
