# Generated by Django 6.0.4 on 2026-04-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_alter_trip_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
