# Generated by Django 6.0.4 on 2026-04-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_alter_trip_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='trip_images/'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
